name: Deploy Azure Function (Backend)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Zip the Azure Function
        working-directory: ./backend
        run: zip -r ../function.zip .

      - name: Confirm ZIP contents
        run: unzip -l function.zip

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: counter-api
          package: function.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
