name: Deploy Frontend to Azure Blob Storage

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload static website to Azure Blob Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
              --destination \$web \
              --source ./frontend \
              --overwrite
